# Generated by Django 5.0.3 on 2024-04-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='leaving_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_of_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
